The amazing comma & Strings and backslashes
buttercrab/wtfpython-ko pull request #20
Opened 2020-08-23 16:24 UTC by jshyunbin

The amazing comma & Strings and backslashes 부분을 번역하였습니다

2020-08-23 23:16 UTC, wooogi123 commented
문자열과 백슬래시 부분의 원문이 삭제되지 않은거 같은데 확인해보시겟어요?

2020-08-24 01:15 UTC, buttercrab requested changes
원문이 삭제되지 않았습니다.

2020-08-24 03:16 UTC, wooogi123 commented
lgtm 😄

2020-08-24 03:37 UTC, buttercrab approved these changes

2020-08-24 03:37 UTC, merged